---
abstract: "A trivial and shameless subclass of DateTime, aiming at encapsulating and adding \"banal\" functionality."
author:
  - "\"aulusoy\" <\"dev (at) ulusoy.name\">"
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Banal-DateTime
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 1
  perl: 5.006
version: 0.10
